variables:
  UBUNTU_VERSION: "24.04"
  _TF_VERSION: 2.18.0
  _TORCH_VERSION: 2.8.0
  _TRITON_VERSION: 2.52.0
  _ONNX_RUNTIME_VERSION: 1.20.1
  DISABLE_CUDA_ARM64: "true"
  DISABLE_TENSORRT_ARM64: "true"
  DISABLE_TORCH_ARM64: "true"
  DISABLE_TF_ARM64: "true"
  DISABLE_ML_ARM64: "true"
